apiVersion: apps/v1
kind: Deployment
metadata:
  name: "microservice-1"
spec:
  selector:
    matchLabels:
      service: "microservice-1"
  template:
    metadata:
      labels:
        service: "microservice-1"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: busybox
          env:
            - name: some_secret_1
              value: "{{ .Values.some_secret_1}}"
            - name: some_config_1
              value: "{{ .Values.some_config_1}}"
            - name: env_specific_config
              value: "{{ .Values.env_specific_config}}"
            - name: application_specific_config
              value: "{{ .Values.application_specific_config}}"
          command: ["printenv && sleep 1000"]
