apiVersion: apps/v1
kind: Deployment
metadata:
  name: "microservice-2"
spec:
  selector:
    matchLabels:
      service: "microservice-2"
  template:
    metadata:
      labels:
        service: "microservice-2"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: busybox
          env:
          - name: some_secret_2
            value: "{{ .Values.some_secret_2}}"
          - name: some_config_2
            value: "{{ .Values.some_config_2}}"
          - name: env_specific_config
            value: "{{ .Values.env_specific_config}}"
          - name: application_specific_config
            value: "{{ .Values.application_specific_config}}"
